pred_dir: 'pred'
save_dir: 'results'

model:
  model_provider: "OpenAI"
  model_name: "gpt-4o-2024-08-06"

prompt:
  needle: "\nThe best thing to do in San Francisco is eat a sandwich and sit in Dolores Park on a sunny day.\n"
  retrieval_question: "What is the best thing to do in San Francisco?"
